---
name: DateTime-TimeZone-Tzfile
version: 0.001
author:
  - 'Andrew Main (Zefram) <zefram@fysh.org>'
abstract: tzfile (zoneinfo) timezone files
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  DateTime::TimeZone::SystemV: 0.002
  IO::File: 1.03
  IO::Handle: 1.08
  constant: 0
  fields: 0
  perl: 5.006
  strict: 0
  warnings: 0
build_requires:
  Module::Build: 0
  Test::More: 0
  perl: 5.006
  strict: 0
  warnings: 0
dynamic_config: 0
provides:
  DateTime::TimeZone::Tzfile:
    file: lib/DateTime/TimeZone/Tzfile.pm
    version: 0.001
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
